name: paryattan_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_icons: ^1.1.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  dio: ^4.0.0
  eva_icons_flutter: ^3.0.2
  antdesign_icons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  fonts:
    - family: Source_Sans_Pro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
          weight: 700
